version: '3'

services:
  admin:
    image: fasbit1/admin:1.0.0
    ports:
      - "3000:3000"
  stellar_api:
    image: fasbit1/stellar_api:1.0.0
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ${PWD}/.env:/usr/src/app/.env  
  backend_api:
    image: fasbit1/backend_api:1.0.0
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ${PWD}/.env:/usr/src/app/.env
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db